# Usa imagem base com Apache e PHP 8.2
FROM php:8.2-apache

# Instala dependências
RUN apt-get update && apt-get install -y git \
    && docker-php-ext-install mysqli pdo pdo_mysql \
    && a2enmod rewrite

# Define diretório de trabalho
WORKDIR /var/www/html

# Clona o projeto do GitHub na pasta Aeroclube
RUN git clone https://github.com/JoaoAlisson1/TrabalhoDockerPHP.git /tmp/projeto \
    && mv /tmp/projeto/public_html /var/www/html/Aeroclube \
    && chown -R www-data:www-data /var/www/html/Aeroclube \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


# Altera o Apache para escutar na porta 8080
RUN sed -i 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf \
    && sed -i 's/:80>/:8080>/' /etc/apache2/sites-enabled/000-default.conf

# Permissões para a pasta do projeto
RUN echo '<Directory "/var/www/html/Aeroclube">\n\
    Options Indexes FollowSymLinks\n\
    AllowOverride All\n\
    Require all granted\n\
</Directory>' >> /etc/apache2/apache2.conf

# Redireciona logs do Apache para stdout/stderr (acessível via volume)
RUN ln -sf /proc/self/fd/1 /var/log/apache2/access.log \
    && ln -sf /proc/self/fd/2 /var/log/apache2/error.log

# Expõe a porta 8080 (interna do container)
EXPOSE 8080

# Inicia o Apache em foreground
ENTRYPOINT ["apache2-foreground"]
